export const LOADING_DATA = 'LOADING_DATA'

export const GET_DATA = 'GET_DATA'

export const GET_LANG = 'GET_LANG'

export const SET_CURRENT_PROG_LANGUAGE = 'SET_CURRENT_PROG_LANGUAGE'

export const SET_FILTERED_LANG_DATA = 'SET_FILTERED_LANG_DATA'

export const SET_FILTERED_REPO_LANG_DATA = 'SET_FILTERED_REPO_LANG_DATA'

export const SET_CURRENT_DATE = 'SET_CURRENT_DATE'

export const CHANGE_THEME_STYLE = 'CHANGE_THEME_STYLE'
